export const SET_LOADING = "SET_LOADING";
export const SET_DOCUMENTS = "SET_DOCUMENTS";
export const REMOVE_STORY = "REMOVE_STORY";
export const HANDLE_PAGE = "HANDLE_PAGE";
export const HANDLE_SEARCH = "HANDLE_SEARCH";